services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.31.1@sha256:b9b0dcac8b20c01ed4777889c8ae6ff74443ed604e11e4b862d9f3068eeb9114
    volumes:
      - /:/root
      - /:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
