services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.40.0@sha256:feedeba4f2a8c6b3a6191647a4e31ee6b925123db4feae04a251343674497908
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
