services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.42.3@sha256:822a6851fe09f967953cb60b596a140aa84cdcc002124ae530ba5b9a70a01d2a
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
