services:
  server:
    image: docker.io/datarhei/restreamer:2.12.0
    volumes:
      - server-config:/core/config
      - server-data:/core/data
    ports:
      - 1935:1935
      - 1936:1936
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  default:
    name: none
    external: true
volumes:
  server-config: null
  server-data: null
