services:
  reverse-proxy-config:
    image: docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
    command: sh -c 'while sleep 3600; do :; done'
networks:
  default:
    name: none
    external: true
