services:
  server:
    image: quay.io/cockpit/ws:332
    volumes:
      - type: bind
        source: /etc/cockpit/cockpit.conf
        target: /etc/cocokpit/cockpit.conf
        read_only: true
        bind:
          create_host_path: false
networks:
  default:
    name: none
    external: true
