services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /admin/cockpit /admin/cockpit/
      caddy.handle: /admin/cockpit/*
      caddy.handle.reverse_proxy: "{{upstreams 9090}}"

networks:
  caddy-ingress:
    external: true
