services:
  server:
    image: docker.io/amir20/dozzle:v8.6.0@sha256:c4600064115a9be914ad775f6bbd15fb96585579ac85d04967b4fec2f807ca1b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
networks:
  default:
    name: none
    external: true
