services:
  server:
    image: docker.io/amir20/dozzle:v8.10.1@sha256:8adb6aa8cf09794ba6231438be8724147f0ffefa7838ba4408877f0f7489d3aa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
networks:
  default:
    name: none
    external: true
