services:
  server:
    image: docker.io/amir20/dozzle:v6.5.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_ENABLE_ACTIONS=true

networks:
  default:
    name: none
    external: true
