services:
  server:
    image: docker.io/amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
networks:
  default:
    name: none
    external: true
