services:
  server:
    image: docker.io/amir20/dozzle:v8.13.4@sha256:36707d180462e764eac81aac793f8352296048404fa4dea1f280fa3cefa7fce3
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
networks:
  default:
    name: none
    external: true
