services:
  server:
    image: docker.io/amir20/dozzle:v8.13.5@sha256:decddbdb4eb80617da9c6894e082920cf356baee76476ec144ce5a2e3bf8c164
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
networks:
  default:
    name: none
    external: true
