# Advertise ourselves as a default route to the internet.

interface=wlan1
dhcp-option=wlan1,option:router,0.0.0.0

interface=wlan0
dhcp-option=wlan0,option:router,0.0.0.0

interface=eth0
dhcp-option=eth0,option:router,0.0.0.0

interface=usb0
dhcp-option=usb0,option:router,0.0.0.0

interface=eth1
dhcp-option=eth1,option:router,0.0.0.0

