services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /admin/portainer /admin/portainer/
      caddy.handle_path: /admin/portainer/*
      caddy.handle_path.reverse_proxy: "{{upstreams 9000}}"

networks:
  caddy-ingress:
    external: true
