services:
  server:
    image: docker.io/portainer/portainer-ce:2.25.1@sha256:c8aefc42eb902fc301a17fe151ceef24f02025feb4c9fdfffe5bd9234d777a42
    command: --tlsskipverify
    volumes:
      - server-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
