services:
  server:
    image: docker.io/portainer/portainer-ce:2.30.0@sha256:d154fed053b371ea6899fe4fee8d9a1709420278a30e19b7002740ee652e493b
    command: --tlsskipverify
    volumes:
      - server-data:/data
      - /run/docker.sock:/run/docker.sock
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
