services:
  server:
    image: docker.io/portainer/portainer-ce:2.31.3@sha256:30e682f04bf1b60d5aa90208ed317e8c61fccd440ceb658323ea64d41d94fcfa
    command: --tlsskipverify
    volumes:
      - server-data:/data
      - /run/docker.sock:/run/docker.sock
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
