services:
  server:
    image: docker.io/portainer/portainer-ce:2.27.1@sha256:99c3047d44991af08f2a34df16e69ae2654bee43444b2e9857aa6b5864c4f602
    command: --tlsskipverify
    volumes:
      - server-data:/data
      - /run/docker.sock:/run/docker.sock
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
