services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.handle_path: /ps/processing/segmenter/streams/object.mjpg
      caddy.handle_path.rewrite: "* /object.mjpg"
      caddy.handle_path.reverse_proxy: "{{upstreams 8001}}"

networks:
  caddy-ingress:
    external: true
