services:
  server:
    image: ghcr.io/planktoscope/device-backend-processing-segmenter:2024.0.0-beta.2@sha256:e13204f9001a5e5c51af7771c0d6332da1c836df92ca38546d01a6c32ff1fa14
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  default:
    name: none
    external: true
