services:
  server:
    image: ghcr.io/planktoscope/device-backend-processing-segmenter:pr-72
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  default:
    name: none
    external: true
