services:
  server:
    volumes:
      - /run/machine-name:/run/machine-name
      - /home/pi/data:/home/pi/data
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
    depends_on:
      bind-mount-setup:
        condition: service_completed_successfully
  bind-mount-setup:
    # This is a workaround for non-rootless Docker creating bind mounts with root ownership:
    image: docker.io/library/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    volumes:
      - /home/pi/data:/home/pi/data
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
    command: 'sh -c "chown -R 1000:1000 /home/pi/data /home/pi/device-backend-logs; sleep 60"'
