services:
  server:
    volumes:
      - type: bind
        source: /run/machine-name
        target: /var/lib/planktoscope/machine-name # FIXME(ethanjli): update the segmenter to read from /run/machine-name
      - /home/pi/data:/home/pi/data
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
    depends_on:
      bind-mount-setup:
        condition: service_completed_successfully
  bind-mount-setup:
    image: docker.io/library/alpine:3.21.3
    volumes:
      - /home/pi/data:/home/pi/data
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
    command: 'sh -c "chown -R 1000:1000 /home/pi/data /home/pi/device-backend-logs"'
