services:
  server:
    volumes:
      - ~/.local/share/planktoscope/device-backend-logs:/home/pi/device-backend-logs
    depends_on:
      logs-bind-mount-setup:
        condition: service_completed_successfully
  logs-bind-mount-setup:
    image: docker.io/library/alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
    volumes:
      - ~/.local/share/planktoscope/device-backend-logs:/home/pi/device-backend-logs
    command: 'sh -c "chown -R 1000:1000 /home/pi/device-backend-logs; sleep 60"'
