services:
  server:
    volumes:
      - ~/.local/share/planktoscope/data:/home/pi/data
    depends_on:
      data-bind-mount-setup:
        condition: service_completed_successfully
  data-bind-mount-setup:
    image: docker.io/library/alpine:3.21.3
    volumes:
      - ~/.local/share/planktoscope/data:/home/pi/data
    command: 'sh -c "chown -R 1000:1000 /home/pi/data"'
