services:
  server:
    image: docker.io/lucaslorentz/caddy-docker-proxy:2.9.2@sha256:a1c9ae00b1f9e3ffe4ab9ff071c06d349e0e7cefbec81fce35546c32155d1792
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
      - server-data:/data
      - server-config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CADDY_DOCKER_SCAN_STOPPED_CONTAINERS=1
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
  server-config: null
