services:
  server:
    image: ghcr.io/sargassum-world/pslocal:0.3.8
    volumes:
      - server_data:/data
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DATABASE_URI: file:/data/db.sqlite3
      LOCALHOST_DEFAULT: host.docker.internal

networks:
  default:
    name: none
    external: true

volumes:
  server_data:
