services:
  node-exporter:
    image: docker.io/prom/node-exporter:v1.7.0@sha256:4cb2b9019f1757be8482419002cb7afe028fdba35d47958829e4cfeaf6246d80
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    labels:
      prometheus-job: node-exporter
      prometheus-__scrape_interval__: 5s
      prometheus-__scrape_timeout__: 5s
      prometheus-__address__: host.docker.internal:9100
networks:
  default:
    name: none
    external: true
