services:
  agent:
    image: docker.io/prom/node-exporter:v1.9.1@sha256:d00a542e409ee618a4edc67da14dd48c5da66726bbd5537ab2af9c1dfc442c8a
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
        bind:
          create_host_path: false
          propagation: rslave
    labels:
      prometheus-job: node-exporter
      prometheus-__scrape_interval__: 5s
      prometheus-__scrape_timeout__: 5s
      prometheus-__address__: host.docker.internal:9100
networks:
  default:
    name: none
    external: true
