services:
  reverse-proxy-config:
    image: docker.io/library/alpine:3.21.1@sha256:b97e2a89d0b9e4011bb88c02ddf01c544b8c781acf1f4d559e7c8f12f1047ac3
    command: sh -c 'while sleep 3600; do :; done'
networks:
  default:
    name: none
    external: true
