services:
  reverse-proxy-config:
    image: docker.io/library/alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
    command: sh -c 'sleep 60'
networks:
  default:
    name: none
    external: true
