services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.33.0@sha256:766a2a52a769156ee1fd33853213b4ce3d29d724c7af88c94ff8680474fd41d1
    volumes:
      - /home/pi/data:/home/pi/data
      - /home/pi/data:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/data
      # We must assign a port which is available to non-root users:
      - FB_PORT=9000
    user: '1000:1000'
    depends_on:
      volume-setup:
        condition: service_completed_successfully
  volume-setup:
    image: docker.io/library/alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
    volumes:
      - server-data:/database
      - /home/pi/data:/home/pi/data
    command: 'sh -c "chown -R 1000:1000 /database /home/pi/data; sleep 60"'
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
