services:
  server:
    image: docker.io/grafana/grafana-oss:10.4.10@sha256:e9b5417327531e1ea588bd617bb1bc3c724fa4de7fac0d96893a887fe5a478ad
    volumes:
      - server-data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
