services:
  server:
    image: docker.io/grafana/grafana-oss:11.2.3@sha256:e655244dc91610d87f9ea4b40d4d375f714329aa1c89dd34ea618a2f76af684b
    volumes:
      - server-data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
