services:
  server:
    image: docker.io/grafana/grafana-oss:11.5.2@sha256:163be84f32fdf9d204c6b8b2f2cccb04628baa365cf973eb1c32d1faaa8fbfc3
    volumes:
      - server-data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
