services:
  server:
    image: docker.io/grafana/grafana-oss:11.5.3@sha256:c319c1539496215b01b5f76294a3d200832322404b91731ca62ca5a9d24cdf7e
    volumes:
      - server-data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
