services:
  server:
    image: docker.io/grafana/grafana-oss:11.6.0@sha256:62d2b9d20a19714ebfe48d1bb405086081bc602aa053e28cf6d73c7537640dfb
    volumes:
      - server-data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
