package:
  description: Metrics monitoring dashboard
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: AGPL-3.0
  sources:
    - https://github.com/grafana/grafana

deployment:
  compose-files: [compose.yml]

features:
  frontend:
    description: Provides access to the GUI
    compose-files: [compose-frontend.yml]
    tags:
      - device-portal-name=System monitoring dashboard
      - device-portal-description=Provides a graphical dashboard for monitoring system and application metrics
      - device-portal-type=Browser applications
      - device-portal-purpose=System administration and troubleshooting
      - device-portal-entrypoint=/admin/grafana/
    requires:
      networks:
        - description: Overlay network for Caddy to connect to upstream services
          name: caddy-ingress
      services:
        - tags: [caddy-docker-proxy]
          port: 80
          protocol: http
    provides:
      services:
        - description: Monitoring dashboard for Prometheus metrics
          port: 80
          protocol: http
          paths:
            - /admin/grafana
            - /admin/grafana/*
  no-login:
    description: Allows full access without user management or login
    compose-files: [compose-no-login.yml]
  prometheus-datasource:
    description: Provides integration with a Prometheus server
    compose-files: [compose-datasource-prometheus.yml]
    requires:
      services:
        - description: Prometheus server
          port: 80
          protocol: http
          paths:
            - /admin/prometheus
            - /admin/prometheus/*
          nonblocking: true
  host-summary-dashboard:
    description: Provides a dashboard to summarize node-exporter metrics; includes prometheus-datasource
    compose-files: [compose-datasource-prometheus.yml, compose-dashboard-host-summary.yml]
    requires:
      services:
        - description: Prometheus server
          port: 80
          protocol: http
          paths:
            - /admin/prometheus
            - /admin/prometheus/*
          nonblocking: true
        - description: Metrics from the Prometheus node-exporter app
          tags: [node-exporter]
          protocol: prometheus-metrics
          nonblocking: true
    provides:
      services:
        - description: Dashboard with summary of host metrics
          tags: [dashboard-host-summary]
          port: 80
          protocol: http
          paths:
            - /admin/grafana/d/host-summary/*
  cpu-limit:
    description: Limits the dashboard's CPU usage to at most one virtual core.
    compose-files: [compose-cpu-limit.yml]
