services:
  mqtt-broker:
    image: docker.io/library/eclipse-mosquitto:2.0.20@sha256:8b396cec28cd5e8e1a3aba1d9abdbddd42c454c80f703e77c1bec56e152fa54e
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log
volumes:
  server-data: null
  server-logs: null
