services:
  mqtt-broker:
    image: docker.io/eclipse-mosquitto:2.0.19@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log
volumes:
  server-data: null
  server-logs: null
