services:
  mqtt-broker:
    image: docker.io/library/eclipse-mosquitto:2.0.20@sha256:090d745b6435d10a31acb82eee999ec36a2d7f416cc4f578c0a298c42af2ea14
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log
volumes:
  server-data: null
  server-logs: null
