services:
  mqtt-broker:
    image: docker.io/library/eclipse-mosquitto:2.0.18
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log

volumes:
  server-data:
  server-logs:
