services:
  server:
    image: docker.io/library/eclipse-mosquitto:2.0.22@sha256:d219d3a72847f3aed6a1d66975972d3b17f86e39e8f6f6b86b4088b879c1a2d6
    command: mosquitto -c /mosquitto-no-auth.conf
    networks:
      - mosquitto
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log
volumes:
  server-data: null
  server-logs: null
networks:
  default:
    name: none
    external: true
  mosquitto:
    name: mosquitto
