services:
  server:
    image: docker.io/library/eclipse-mosquitto:2.0.20@sha256:21421af7b32bf9ce508e9090c8eb13bb81f410ca778dc205506180a6f862d0eb
    command: mosquitto -c /mosquitto-no-auth.conf
    networks:
      - mosquitto
    volumes:
      - server-data:/mosquitto/data
      - server-logs:/mosquitto/log
volumes:
  server-data: null
  server-logs: null
networks:
  default:
    name: none
    external: true
  mosquitto:
    name: mosquitto
