package:
  description: MQTT broker for pub-sub services
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: EPL-2.0 OR BSD-3-Clause
  sources:
    - https://github.com/eclipse/mosquitto

deployment:
  compose-files:
    - deployment.compose.yml
  provides:
    networks:
      - description: Bridge network for access to the MQTT broker
        name: mosquitto

features:
  mqtt-broker:
    description: Provides access to the MQTT broker from the host
    compose-files:
      - mqtt-broker.compose.yml
    tags:
      - device-portal-name=MQTT broker
      - device-portal-description=Provides a broker for MQTT messages on port 1883
      - device-portal-type=System infrastructure
      - device-portal-purpose=Networking
    provides:
      listeners:
        - description: MQTT broker
          port: 1883
          protocol: mqtt
      services:
        - description: MQTT broker for the PlanktoScope backend's MQTT API
          tags: [mqtt-broker]
          port: 1883
          protocol: mqtt
  firewall-allow-direct:
    description:
      Firewall configuration to allow accessing the MQTT broker from directly-connected devices
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the nm-shared zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/nm-shared
    provides:
      file-exports:
        - description: Drop-in XML fragment for firewalld's MQTT service
          target: overlays/etc/firewalld/zones.d/nm-shared/61-service-mqtt.xml
  firewall-allow-public:
    description:
      Firewall configuration to allow public access to the MQTT broker
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the public zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/public
    provides:
      file-exports:
        - description: Drop-in XML fragment for firewalld's MQTT service
          target: overlays/etc/firewalld/zones.d/public/61-service-mqtt.xml
