package:
  description: MQTT broker ambiently provided by the PlanktoScope
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: EPL-2.0 OR BSD-3-Clause
  sources:
    - https://github.com/eclipse/mosquitto

deployment:
  compose-files: [compose.yml]

features:
  mqtt-broker:
    description: Provides access to the MQTT broker
    compose-files: [compose-mqtt-broker.yml]
    tags:
      - device-portal-name=MQTT broker
      - device-portal-description=Provides a broker for MQTT messages on port 1883
      - device-portal-type=System infrastructure
      - device-portal-purpose=Networking
    provides:
      listeners:
        - description: MQTT broker
          port: 1883
          protocol: mqtt
      services:
        - description: MQTT broker for the PlanktoScope backend's MQTT API
          tags: [mqtt-broker]
          port: 1883
          protocol: mqtt
