services:
  hello:
    image: nginxdemos/hello:0.4@sha256:91247f025eaa5e7677557d5a7ec8696708c40da724dc7f0b7b77c24498274147
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
