services:
  hello:
    image: nginxdemos/hello:0.4@sha256:f89cb9c05c54d591f5408b821b583beaf951f81733efd4062c1c61ce988ce682
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
