services:
  whoami:
    image: traefik/whoami:v1.10.3@sha256:43a68d10b9dfcfc3ffbfe4dd42100dc9aeaf29b3a5636c856337a5940f1b4f1c
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/whoami /demo/whoami/
      caddy.handle_path: /demo/whoami/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
