services:
  hello:
    image: nginxdemos/hello:0.4@sha256:219ca8793045e4e9ea6bc72f4a494f83c2e987588d122a441f249f0bc2b8e19e
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
