services:
  hello:
    image: nginxdemos/hello:0.4@sha256:eb682813e993d56b77e3c35e46f9e88bafec329195453d5db7339ea0dce08f4c
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
