services:
  hello:
    image: nginxdemos/hello:0.4@sha256:3601e60e6d7da89919d5dbe3ccde44f9446995af0138da3135985613bb2a068f
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
