services:
  hello:
    image: nginxdemos/hello:0.4@sha256:27984e326bb77db2c9e1c669ee63fd1dc6708b9ed2c1315b81e30b1eef75f947
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/hello-nginx /demo/hello-nginx/
      caddy.handle_path: /demo/hello-nginx/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy-ingress:
    external: true
