services:
  server:
    image: ghcr.io/planktoscope/project-docs:sha-776c201-minimal@sha256:47f43c7d7e87aa112607835fb68d5a134efcb788e171ead94482abfa6fad8d5f
    volumes:
      - server-data:/data
      - server-config:/config
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
  server-config: null
