services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.32.0@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b
    volumes:
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
      - /home/pi/device-backend-logs:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/device-backend-logs
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
