services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.32.0@sha256:593478e3c24c5ea9f5d7478dc549965b7bc7030707291006ce8d0b6162d3454b
    volumes:
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
      - type: bind
        source: /home/pi/device-backend-logs
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/device-backend-logs
      # We must assign a port which is available to non-root users:
      - FB_PORT=9000
    user: '1000:1000'
    depends_on:
      volume-setup:
        condition: service_completed_successfully
  volume-setup:
    image: docker.io/library/alpine:3.21.3
    volumes:
      - server-data:/database
    command: 'sh -c "chown -R 1000:1000 /database"'
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
