services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.33.5@sha256:659a58c71b974dbf5fb0fd5453fec91e84b8c3729f74bb610f16e214352e56bd
    volumes:
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
      - /home/pi/device-backend-logs:/srv # this prevents filebrowser from making an unnamed volume
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/device-backend-logs
      # We must assign a port which is available to non-root users:
      - FB_PORT=9000
    user: '1000:1000'
    depends_on:
      volume-setup:
        condition: service_completed_successfully
  volume-setup:
    image: docker.io/library/alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
    volumes:
      - server-data:/database
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
    command: 'sh -c "chown -R 1000:1000 /database /home/pi/device-backend-logs; sleep 60"'
networks:
  default:
    name: none
    external: true
volumes:
  server-data: {}
