name: check

on:
  push:
    branches:
      - main
      - edge
      - beta
      - stable
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        forklift-version: [0.5.0, 0.4.0]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v0.1.0
        with:
          version: ${{ matrix.forklift-version }}

      - name: Cache Forklift repos
        run: forklift dev plt cache-repo

      - name: Run Forklift checks
        run: |
          forklift dev plt check

      - name: Dry-run Forklift plans from an empty host
        run: |
          forklift dev plt plan --parallel
          forklift dev plt plan
